### ISSUE TITLE
Error during assembly

### ISSUE THREAD

**Issue by MalbertR** [metagenome-atlas/Tutorial_Finnland#9]
```
Traceback (most recent call last):
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/workflow.py", line 1056, in execute
    success = scheduler.schedule()
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/scheduler.py", line 501, in schedule
    self.run(runjobs)
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/scheduler.py", line 518, in run
    executor.run_jobs(
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 149, in run_jobs
    self.run(
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 978, in run
    jobscript = self.get_jobscript(job)
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 752, in get_jobscript
    f = job.format_wildcards(self.jobname, cluster=self.cluster_wildcards(job))
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 859, in cluster_wildcards
    return Wildcards(fromdict=self.cluster_params(job))
  File "/scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 835, in cluster_params
    cluster.update(self.cluster_config.get(job.name, dict()))
ValueError: need more than 1 value to unpack
[2021-09-27 14:27 CRITICAL] Command 'snakemake --snakefile /scratch/project_2004930/miniconda3/envs/atlasenv/lib/python3.8/site-packages/atlas/Snakefile --directory /users/student196/first_run --jobs 40 --rerun-incomplete --configfile '/users/student196/first_run/config.yaml' --nolock  --profile cluster --use-conda --conda-prefix /scratch/project_2004930/databases/conda_envs   --scheduler greedy  assembly   ' returned non-zero exit status 1.

```

**Comment by MalbertR** [comment]
I think I fixed it. It was indeed a typo in the cluster_config file.
